In [5]:
# pytorch 확인
import torch

# GPU 사용 가능한지 확인
if torch.cuda.is_available():
    print("✅ GPU 사용 가능")
    print("사용 중인 GPU:", torch.cuda.get_device_name(0))
    print(torch.__version__)
else:
    print("❌ GPU 사용 불가")

# 예시: 간단한 연산을 GPU에서 수행
x = torch.rand(3, 3).to('cuda' if torch.cuda.is_available() else 'cpu')
y = torch.rand(3, 3).to('cuda' if torch.cuda.is_available() else 'cpu')
z = x + y
print("연산 결과:", z)
print("연산이 수행된 디바이스:", z.device)


✅ GPU 사용 가능
사용 중인 GPU: NVIDIA GeForce RTX 4060 Laptop GPU
2.7.1+cu126
연산 결과: tensor([[0.8268, 0.5871, 0.6922],
        [0.6064, 1.0118, 0.8154],
        [0.3374, 1.2387, 0.7652]], device='cuda:0')
연산이 수행된 디바이스: cuda:0


In [2]:
# tensorflow 확인
import tensorflow as tf
print("TF version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))


2025-06-08 19:30:12.631933: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-08 19:30:12.760872: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-08 19:30:12.760926: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-08 19:30:12.783044: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-08 19:30:12.829313: I tensorflow/core/platform/cpu_feature_guar

TF version: 2.15.0
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


2025-06-08 19:30:14.189026: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-06-08 19:30:14.191939: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-06-08 19:30:14.192053: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [ ]:
# YOLO 확인
from ultralytics import YOLO
import cv2

# 모델 로드 (예: nano 모델)
model = YOLO("yolov8n.pt")  # 또는 yolov8s.pt, yolov8m.pt 등

# 웹캠 열기 (기본 카메라는 0)
cap = cv2.VideoCapture(2)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # YOLO로 프레임 추론
    results = model(frame, verbose=False)

    # 결과를 시각화한 이미지 얻기
    annotated_frame = results[0].plot()

    # 화면에 출력
    cv2.imshow("YOLOv8 Webcam", annotated_frame)

    # 종료 조건 (ESC 키)
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()


In [3]:
import tensorflow as tf

# TensorFlow 버전 출력
print("TensorFlow version:", tf.__version__)

# 사용 가능한 GPU 디바이스 목록 출력
gpus = tf.config.list_physical_devices('GPU')
print("GPU available:", gpus)

# 간단한 GPU 연산 테스트
if gpus:
    with tf.device('/GPU:0'):
        a = tf.random.normal([3, 3])
        b = tf.random.normal([3, 3])
        c = tf.matmul(a, b)
        print("Result on GPU:\n", c)
else:
    print("No GPU found. Running on CPU.")


TensorFlow version: 2.15.0
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Result on GPU:
 tf.Tensor(
[[ 1.863162  -2.2528744  2.8599558]
 [ 2.2718885 -2.2292876  1.6935599]
 [-3.2471611  1.1127292 -1.0638674]], shape=(3, 3), dtype=float32)


2025-06-07 02:30:03.247552: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-06-07 02:30:03.247683: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-06-07 02:30:03.247736: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [1]:
# camera 연결 확인
import cv2

cap = cv2.VideoCapture('/dev/video0')
if not cap.isOpened():
    print("❌ 카메라 열기 실패")
else:
    print("✅ 카메라 연결 성공")
    cap.release()
    cv2.destroyAllWindows()

✅ 카메라 연결 성공


In [ ]:
# camera FPS 확인
cap = cv2.VideoCapture('/dev/video0')
fps = cap.get(cv2.CAP_PROP_FPS)
print("카메라 FPS:", fps)

카메라 FPS: 0.0


In [4]:
import cv2

# 0번 카메라 열기 (기본 웹캠)
cap = cv2.VideoCapture('/dev/video2')

if not cap.isOpened():
    print("❌ 카메라를 열 수 없습니다.")
    exit()

while True:
    ret, frame = cap.read()
    if not ret:
        print("❌ 프레임을 읽을 수 없습니다.")
        break

    # 영상 출력
    cv2.imshow("Camera", frame)

    # 'q' 키 누르면 종료
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 자원 해제
cap.release()
cv2.destroyAllWindows()
